-- Drop all data from database
DROP TABLE IF EXISTS UserSchedule;
DROP TABLE IF EXISTS ClassTime;
DROP TABLE IF EXISTS Class;
DROP TABLE IF EXISTS Instructor;
DROP TABLE IF EXISTS CoursesTaken;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS AppUser;