-- Drop all data from database
DROP TABLE IF EXISTS UserSchedule CASCADE;
DROP TABLE IF EXISTS ClassTime CASCADE;
DROP TABLE IF EXISTS Class CASCADE;
DROP TABLE IF EXISTS Instructor CASCADE;
DROP TABLE IF EXISTS CoursesTaken CASCADE;
DROP TABLE IF EXISTS Course CASCADE;
DROP TABLE IF EXISTS AppUser CASCADE;